version: '3.7'
services:
  hls:
    container_name: hls_proxy
    build: ./
    ports:
      - '88:8085'
#    dns:
#      - 1.1.1.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/opt/hlsp/
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t

